name: Deploy to testnet

on:
  push:
    branches:
      - 'develop'
jobs:
  build:
    uses: ./.github/workflows/magickbase-build.yaml
    secrets: inherit
  deploy-update:
    needs: build
    strategy:
      matrix:
        workload: [agents]
    uses: ./.github/workflows/magickbase-deploy.yaml
    with:
      k8s-namespace: testnet
      k8s-workload: ${{ matrix.workload }}
      image-tag: ${{ needs.build.outputs.image-tag }}
    secrets: inherit
